export let Questions = [
    {   
        question_no: "1",
        question:"Which one of the following river flows between Vindhyan and Satpura ranges?",
        type:"radio",
        options:["Narmada","Mahanadi","Son","Netravati"],

    },
    {
        question_no: "2",
        question:"The Central Rice Research Station is situated in?",
        type:"radio",
        options:["Chennai","Cuttack","Bangalore","Quilon"],
    },
    {
        question_no: "3",
        question:"Who among the following wrote Sanskrit grammar?",
        type:"radio",
        options:["Kalidasa","Charak","Panini","Aryabhatt"],
    },
    {
        question_no: "4",
        question:"Which among the following headstreams meets the Ganges in last?",
        type:"radio",
        options:["Alaknanda","Pindar","Mandakini","Bhagirathi"],
    },
    {
        question_no: "5",
        question:"The metal whose salts are sensitive to light is?",
        type:"radio",
        options:["Zinc","Silver","Copper","Aluminum"],
    },
    {
        question_no: "6",
        question:"Which of the following team won the T20 2021?",
        type:"radio",
        options:["India","Australia","England","South Africa"],
    },
    {
        question_no: "7",
        question:" Which is first Indian cricket tournament?",
        type:"radio",
        options:["Bombay Series","Bombay Triangular","None of these","Pepsi Cup"],
    },
    {
        question_no: "8",
        question:"Which of the following is first cricket club in India?",
        type:"radio",
        options:["East Indian Cricket Club","Oriental Cricket Club","Maharashtra Cricket Club","Bombay Cricket Club"],
    },
    {
        question_no: "9",
        question:"Indian played first test match against which team",
        type:"radio",
        options:["South Africa","England","Pakistan","Australia"],
    },
    {
        question_no: "10",
        question:"Indian played their First ODI Match against which team",
        type:"radio",
        options:["England","Pakistan","Australia","South Africa"],
    },
    {
        question_no: "11",
        question:"Who is first Indian batsman to hit 6 sixes in an over?",
        type:"radio",
        options:["Yuvraj Singh","Shikhar Dhawan","Ajit Agarkar","None of these"],
    },
    {
        question_no: "12",
        question:"The country that has the highest in Barley Production?",
        type:"radio",
        options:["China","India","Russia","France"],
    },
    {
        question_no: "13",
        question:"Players who captained Chennai Super Kings in IPL 2022",
        type:"checkbox",
        options:["Mahendra Singh Dhoni","Ruturaj Gaikwad","Ravindra Jadeja","Devon Conway"],
    },
    {
        question_no: "14",
        question:"Tsunamis are not caused by",
        type:"radio",
        options:["Hurricanes","Earthquakes","Undersea landslides","Volcanic eruptions"],
    },
    {
        question_no: "15",
        question:"Chambal river is a part of –",
        type:"radio",
        options:["Sabarmati basin","Ganga basin","Narmada basin","Godavari basin"],
    },
    {
        question_no: "16",
        question:"D.D.T. was invented by?",
        type:"radio",
        options:["Mosley","Rudolf","Karl Benz","Dalton"],
    },
    {
        question_no: "17",
        question:"Volcanic eruption do not occur in the",
        type:"radio",
        options:["Baltic sea","Black sea","Caribbean sea","Caspian sea"],
    },
    {
        question_no: "18",
        question:"IPL 2021 final is played between which teams",
        type:"checkbox",
        options:["Kolkata Knight Riders","Royal Challengers Bangalore","Chennai Super Kings","Rajasthan Royals"],
    },
    {
        question_no: "19",
        question:"Indus river originates in –",
        type:"radio",
        options:["Kinnaur","Ladakh","Nepal","Tibet"],
    },
    {
        question_no: "20",
        question:"The hottest planet in the solar system?",
        type:"radio",
        options:["Mercury","Venus","Mars","Jupiter"],
    },
    {
        question_no: "21",
        question:"Where was the electricity supply first introduced in India –",
        type:"radio",
        options:["Mumbai","Dehradun","Darjeeling","Chennai"],
    },
    {
        question_no: "22",
        question:"Which of the following is related to Bharat Nirman Scheme?",
        type:"radio",
        options:["Foodgrain production self sufficiency","Family welfare programme","Infrastructure development","Employment generation program"],
    },
    {
        question_no: "23",
        question:"Which peninsular river is least seasonal in flow?",
        type:"radio",
        options:["Narmada","Krishna","Godavari","Cauvery"],
    },
    {
        question_no: "24",
        question:"Which of the following is not a nuclear power center?",
        type:"radio",
        options:["Narora","Kota","Chamera","Kakrapara"],
    },
    {
        question_no: "25",
        question:"FFC stands for",
        type:"radio",
        options:["Federation of Football Council","Film Finance Corporation","Foreign Finance Corporation","None of the above"],
    },
]